import { Ticket, PlaneTakeoff, DollarSign, Users as UsersIcon } from 'lucide-react'
import StatCard from '../components/StatCard.jsx'
import ChartCard from '../components/ChartCard.jsx'
import RecentActivity from '../components/RecentActivity.jsx'
import {
  statCardsData,
  bookingTrendsData,
  ticketDistributionData,
  recentActivitiesData
} from '../data/dashboardData.js'

export default function Dashboard() {
  // Map our type strings to specific Lucide icons
  const iconMap = {
    bookings: Ticket,
    flights: PlaneTakeoff,
    revenue: DollarSign,
    users: UsersIcon
  }

  // Get current date string for header
  const currentDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  return (
    <div className="space-y-6">
      {/* Welcome Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 bg-white p-6 border border-slate-200 rounded-xl shadow-sm">
        <div>
          <h1 className="text-xl font-extrabold text-slate-900 tracking-tight">Operations Console</h1>
          <p className="text-xs font-semibold text-slate-400 mt-1">
            Real-time control tower overview for global bookings and flight routes.
          </p>
        </div>
        <div className="text-left md:text-right font-medium text-slate-500 text-xs">
          <p className="font-bold text-slate-700">{currentDate}</p>
          <p className="text-[10px] text-green-600 flex items-center gap-1 mt-0.5 font-bold">
            <span className="w-1.5 h-1.5 bg-green-500 rounded-full inline-block" /> All services online
          </p>
        </div>
      </div>

      {/* Statistics Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {statCardsData.map((stat, i) => (
          <StatCard
            key={i}
            title={stat.title}
            value={stat.value}
            change={stat.change}
            isPositive={stat.isPositive}
            timeframe={stat.timeframe}
            icon={iconMap[stat.type] || Ticket}
          />
        ))}
      </div>

      {/* Analytics Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ChartCard
          title="Booking Traffic Trends"
          subtitle="Monthly overview comparing total bookings initiated against completed trips (Jan-Jun)"
          type="area"
          data={bookingTrendsData}
        />
        <ChartCard
          title="Revenue Generated by Ticket Class"
          subtitle="Operational revenue allocation generated across Economy, Business, and First Class"
          type="bar"
          data={ticketDistributionData}
        />
      </div>

      {/* Bottom Table: Recent Operations Activity */}
      <RecentActivity activities={recentActivitiesData} />
    </div>
  )
}
